drop table Person;

create table Person(
id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
name varchar,
age int
);

select * from Person;

select * from Person; - Проверка добавились ли новые люди


create table Person1(
id int PRIMARY KEY,    - Создание новой таблицы для стратегии sequence
name varchar,
age int
);

create sequence person1_id_seq; - Создание объекта sequence вручную для генерации id в таблице Person1

select * from Person1;