package model;

import jakarta.persistence.*;

@Entity // Аннотация помечает те классы, которые связаны с БД (англ. Сущность)
@Table(name="Person") // Аннотация указывает название таблицы в БД
public class Person {

    @Id // Аннотация показывает Hibernate, что столбец является первичным ключом PRIMARY KEY
    @Column(name = "id") // Аннотация для сопоставления поля колонке из таблицы БД
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Поскольку теперь PostgreSQL теперь сам генерирует id нужно указать аннотацию @GeneratedValue,
    //а в качестве аргумента указать стратегию генерации. Стратегия GenerationType.IDENTITY
    //соответствует параметрам новой созданной таблицы с GENERATED BY DEFAULT AS IDENTITY. Это
    //дает понять Hibernate что эту колонку трогать не нужна и она генерируется на стороне PostgreSQL
    private int id;
    @Column(name = "name")
    private String name;
    @Column(name = "age")
    private int age;
    // Все классы помеченные аннотацией @Entity должны содержать пустой конструктор и поле id.
    // Hibernate может работать только с теми классами, которые помечены аннотаций @Entity

    public Person(){}

    public Person(String name, int age) { // Убрали id из конструктора, так как его теперь не передаем, а он генерируется на стороне PostgreSQL
        this.id = id;
        this.name = name;
        this.age = age;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return this.name + ", "+ this.age;
    }
}
